version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: my-bills-postgres-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - my-bills-postgres-data:/var/lib/postgresql/data
    networks:
      - my-bills-spring-network

volumes:
  my-bills-postgres-data:
    driver: local

networks:
  my-bills-spring-network:
    driver: bridge
